### ISSUE TITLE
Tip: unlock stm32 from under mac/linux

### ISSUE THREAD

**Issue by ysoldak** [arkorobotics/MiniDeltaBootloader#1]
Thanks for the repo, I'm using your pictures of pinouts and learned about openocd from here.

Yesterday, I've successfully flashed MPMD with FW from https://github.com/mcheah/Marlin4MPMD

And I had to make one extra step to unlock the board, I don't see you mention in your instructions.

So, here it goes:
`stm32f0x unlock 0`
and powercycle

After that I was able to flash with `flash write_bank`.

Also did that `mass_erase` trying exactly unlock the board, don't think i worked really since the bard was locked. And seems like that mass erase step is optional.

**Comment by arkorobotics** [comment]
Great catch, my log files show that I ran this command the first time I started experimenting with the chip. I've updated the readme with this change. Thanks!

**Comment by ysoldak** [comment]
Closing the ticket :)
